name: Build and Deploy Salatontime Angular App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Step 1: Build Docker image
      - name: Build Docker image
        run: docker build -t salatontime-frontend ./salatontime-frontend

      # Step 2: Remove old Docker container
      - name: Remove old Docker container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^salatontime-frontend$'; then
            docker rm -f salatontime-frontend
          fi

      # Step 3: Create application-specific network (optional, if required)
      # - name: Create app network
      #   run: docker network create salatontime-network > /dev/null 2>&1 || echo done

      # Step 4: Run Docker container
      - name: Run Docker container
        run: |
          docker run \
            --name salatontime-frontend \
            --network=reverse-proxy-network \
            --label traefik.enable=true \
            --label traefik.docker.network=reverse-proxy-network \
            --label "traefik.http.routers.salatontime-frontend.rule=Host(\"arafat.be\")" \
            --label traefik.http.routers.salatontime-frontend.tls=true \
            --label traefik.http.routers.salatontime-frontend.entrypoints=websecure \
            --label traefik.http.routers.salatontime-frontend.tls.certresolver=letsencrypt \
            -d salatontime-frontend:latest

      # Step 5: Connect app to reverse proxy network (if needed)
      # - name: Connect app to reverse proxy network
      #   run: docker network connect reverse-proxy-network salatontime-frontend > /dev/null 2>&1 || echo done
