name: Create and Deploy Angular Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Step 1: Build Docker image
      - name: Build Docker image
        working-directory: ./salatontime-frontend
        run: docker build -t salatontime-frontend .

      # Step 2: Remove old Docker container
      - name: Remove old Docker container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^salatontime-frontend$'; then
            docker rm -f salatontime-frontend
          fi

      # Step 4: Run Docker container
      - name: Run Docker container
        run: |
          docker run \
            --name salatontime-frontend \
            --network=reverse-proxy-network \
            --label traefik.enable=true \
            --label traefik.docker.network=reverse-proxy-network \
            --label "traefik.http.routers.salatontime-frontend.rule=Host(\"arafat.be\")" \
            --label traefik.http.routers.salatontime-frontend.tls=true \
            --label traefik.http.routers.salatontime-frontend.entrypoints=websecure \
            --label traefik.http.routers.salatontime-frontend.tls.certresolver=letsencrypt \
            -d salatontime-frontend:latest
